SOZO-138 | rewrite planner to output highlevel actions
codeuniversity/control-high pull request #6
Opened 2019-11-22 18:35 UTC by davidlkang

2019-11-22 18:46 UTC, alexmorten requested changes

2019-11-22 18:46 UTC, alexmorten commented on hlc/plan/planner.py
> +TURN_RIGHT = 'turn right 90degree'
```suggestion
TURN_RIGHT = 'turn right 90 degrees'
```
maybe?

2019-11-22 18:46 UTC, alexmorten commented on hlc/tests/test_planner.py
> +def change_orientation(orientation):
This looks like a right turn to me

2019-11-22 18:46 UTC, alexmorten commented on hlc/tests/test_planner.py
> +        if action == "turn right 90degree":
this should reference the constant

2019-11-22 18:46 UTC, alexmorten commented on hlc/tests/test_planner.py
> +        for y in range(7):
? `test_dead_end_6x6 `

2019-11-22 18:46 UTC, alexmorten commented on hlc/tests/test_planner.py
> +        if action == "turn right 90degree":
Should reference the constant

2019-11-22 19:31 UTC, elli-wolf commented on hlc/plan/planner.py
> +    max_layer = math.floor(max(grid_dimension)/2)
```suggestion
    max_layer = max(grid_dimension) // 2
```

2019-11-22 19:31 UTC, elli-wolf commented on hlc/plan/planner.py
> +        if pos == add_pos_tuple(start_pos, (1,0)):
Maybe you should explain what this if-clausel in a comment - it's not very readable

2019-11-22 19:31 UTC, elli-wolf commented on hlc/tests/test_planner.py
> +            keys_grid.append((x, y))
Should reference `grid_dimensions` and this function also generates a grid 5x6, not 4x5.

2019-11-22 19:48 UTC, davidlkang commented on hlc/tests/test_planner.py
> +def change_orientation(orientation):
No. This is a right turn.

2019-11-24 14:07 UTC, katethemate commented on hlc/plan/planner.py
> +        if pos == add_pos_tuple(start_pos, (1,0)):
There is a space missing before 0 in the tuple.

2019-11-24 14:57 UTC, alexmorten approved these changes

2019-11-24 15:01 UTC, merged